### ISSUE TITLE
Image Upload - from ionic2-native Camera / image picker to Meteor

### ISSUE THREAD

**Issue by mmazloum** [Urigo/Ionic2CLI-Meteor-WhatsApp#10]
Hi,

I'm trying to manage image upload, playing with jalik-ufs meteor package, if someone tested it, help would be appreciated, if an easier way exists, advices welcome.

Can't figure out how to install the module.

thanks.

**Comment by dotansimha** [comment]
@mmazloum, please refer to the instructions in [Socially 2 File Upload](https://angular-meteor.com/tutorials/socially/angular2/files-and-uploadfs) step, it describes how to use `jalik:ufs`.
I recommend you to start with regular images store (without thumbnails, add them later).
The usage from the Ionic client side should be the same.

Please re-open the issue if you still in trouble with this one.
