### ISSUE TITLE
Usins meteor and angular 2 without ionic ??

### ISSUE THREAD

**Issue by gotenxds** [Urigo/Ionic2CLI-Meteor-WhatsApp#102]
Hi, in this tutorial it seems we have to use ionic to use meteor, is there some way not to use it ?

**Comment by Ozonix** [comment]
https://angular-meteor.com/tutorials/socially/angular2/bootstrap

**Comment by darkbasic** [comment]
https://angular-meteor.com/tutorials/whatsapp2/meteor/setup
