### ISSUE TITLE
Typescript error: requestPhoneVerification stage 7 of tutorial

### ISSUE THREAD

**Issue by pkitatta** [Urigo/Ionic2CLI-Meteor-WhatsApp#104]
Hi, anyone have a clue on how I can solve this:

Typescript Error
Property 'requestPhoneVerification' does not exist on type 'typeof Accounts'.
C:/Users/Paul/frontend/front2/src/services/phone.ts
 return new Promise<void>((resolve, reject) => {
 
     Accounts.requestPhoneVerification(phoneNumber, (e: Error) => {
 
         if (e) {
 
Typescript Error
Property 'verifyPhone' does not exist on type 'typeof Accounts'.
C:/Users/Paul/frontend/front2/src/services/phone.ts
 return new Promise<void>((resolve, reject) => {
 
     Accounts.verifyPhone(phoneNumber, code, (e: Error) => {
 
         if (e) {

**Comment by airstep** [comment]
For me requestPhoneVerification don't returned any results...

**Comment by pkitatta** [comment]
Solved it.

I have to say that this was brought about by the ;

Cannot find type definition file for '@types/meteor-accounts-phone'
Cannot find type definition file for '@types/underscore'

-an error that I had failed to get rid of earlier.

Most of the headache came from the tsconfig.json file at the "types" section:
This area:-

"types": [
      "@types/underscore"
    ]

I replaced "types" with "typeRoots" like so:

"typeRoots": [
      "node_modules/@types"
    ]

At this point the app behaved - up until this point in step 8.... Anybody with an idea how to solve this: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/56
