### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by aparnapatil01** [Urigo/Ionic2CLI-Meteor-WhatsApp#106]
The link at the top of the **chats page** from tutorial is broken. Please find the screenshot attached here.

![chats_page](https://user-images.githubusercontent.com/10381078/27781721-de9a3b3e-5fec-11e7-9774-10ced8912ac9.png)

**Comment by darkbasic** [comment]
https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/97
