### ISSUE TITLE
Integration of Ionic and Meteor social (Facebook) authentication 

### ISSUE THREAD

**Issue by yuyinitos** [Urigo/Ionic2CLI-Meteor-WhatsApp#11]
Great tutorial! It would be interesting to know how to integrate Facebook authentication in this Ionic/Meteor setup (Ionic CLI). My efforts failed, it's kind of tricky.

**Comment by dotansimha** [comment]
The tricky part is to use Meteor packages in the client side, without Meteor.
Did you try https://github.com/mixersoft/accounts-facebook-client-side ?

**Comment by dotansimha** [comment]
@yuyinitos I am closing at the moment. I the new tutorial we are using meteor packages in a different way, which allows you to use Meteor's client side bundle instead of pre-built package.

**Comment by mordka** [comment]
@dotansimha The new tutorial doesn't mention OAuth and it seems like we need client only solution, OAuth redirects back to port 3000. Has anyone got a solution?
