### ISSUE TITLE
Runtime Error can't convert undefined to object

### ISSUE THREAD

**Issue by hwonda** [Urigo/Ionic2CLI-Meteor-WhatsApp#120]
Hello 

I have got this project working several time with modifications and all of a sudden out of the blues i get this error: "Runtime Error can't convert undefined to object"

D/<@http://localhost:8100/build/polyfills.js:1:3456
_redefine.js/_module39.exports@http://localhost:8100/build/main.js:110785:31
$export@http://localhost:8100/build/main.js:110574:29
_typed-array.js/_module128.exports@http://localhost:8100/build/main.js:116726:17
es6.typed.uint8-array.js@http://localhost:8100/build/main.js:116186:13
fileEvaluate@http://localhost:8100/build/main.js:106622:11
_require@http://localhost:8100/build/main.js:106505:18
runtime.js@http://localhost:8100/build/main.js:123827:13
fileEvaluate@http://localhost:8100/build/main.js:106622:11
_require@http://localhost:8100/build/main.js:106505:18
@http://localhost:8100/build/main.js:123834:19
@http://localhost:8100/build/main.js:123747:2
@http://localhost:8100/build/main.js:101062:29
__webpack_require__@http://localhost:8100/build/main.js:20:12
@http://localhost:8100/build/main.js:101042:1
__webpack_require__@http://localhost:8100/build/main.js:20:12
@http://localhost:8100/build/main.js:63:18
@http://localhost:8100/build/main.js:1:11

Tried and crosschecked everything. Does anyone have this troubling error and how have you resolved it?

Thanks

**Comment by darkbasic** [comment]
Let's track it here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/124#issuecomment-331118105
