### ISSUE TITLE
Project error on iOS version 10.3.3 and Android version 4.4.4

### ISSUE THREAD

**Issue by fernandoarevalo** [Urigo/Ionic2CLI-Meteor-WhatsApp#121]
Hi everyone

I am doing the tutorial whit the Ionic 3 Version (Last Update: 15.06.2017). After install it on iOS (Iphone 6 version 10.3.3) and Android (Samsung Galaxy S3 version 4.4.4) devices, i am getting **WHITE SCREEN** and these errors.

### iOS - Xcode console
```
2017-08-12 17:24:34.407809-0500 MyApp[317:50657] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/8185661C-F89D-438E-8109-53BC4A470722/Library/Cookies/Cookies.binarycookies
2017-08-12 17:24:34.554944-0500 MyApp[317:50657] Apache Cordova native platform version 4.4.0 is starting.
2017-08-12 17:24:34.556014-0500 MyApp[317:50657] Multi-tasking -> Device: YES, App: YES
2017-08-12 17:24:34.854015-0500 MyApp[317:50657] Using UIWebView
2017-08-12 17:24:34.857185-0500 MyApp[317:50657] [CDVTimer][handleopenurl] 0.227034ms
2017-08-12 17:24:34.860531-0500 MyApp[317:50657] [CDVTimer][intentandnavigationfilter] 3.229976ms
2017-08-12 17:24:34.860723-0500 MyApp[317:50657] [CDVTimer][gesturehandler] 0.102997ms
2017-08-12 17:24:34.883088-0500 MyApp[317:50657] [CDVTimer][splashscreen] 22.305012ms
2017-08-12 17:24:34.893854-0500 MyApp[317:50657] [CDVTimer][statusbar] 10.562003ms
2017-08-12 17:24:34.895575-0500 MyApp[317:50657] [CDVTimer][keyboard] 1.525998ms
2017-08-12 17:24:34.895740-0500 MyApp[317:50657] [CDVTimer][TotalPluginStartup] 38.825989ms
2017-08-12 17:24:39.115410-0500 MyApp[317:50697] libMobileGestalt MobileGestaltSupport.m:153: pid 317 (MyApp) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
2017-08-12 17:24:39.115508-0500 MyApp[317:50697] libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
2017-08-12 17:24:42.406886-0500 MyApp[317:50657] Resetting plugins due to page load.
2017-08-12 17:24:43.172301-0500 MyApp[317:50657] Finished load of: file:///var/containers/Bundle/Application/4DBE3351-781F-4A48-93DF-4E8134F24893/MyApp.app/www/index.html
```
### Android - Chrome inspect console

```
Uncaught TypeError: Cannot convert undefined or null to object      polyfills.js:1
```

This project  has been tested also on
- Sony Xperia M4 Aqua (Android version 5.0)
- Lenovo vibe K5(Android version 5.1.1)

and everything works fine.

I really appreciate any help whit this issue. Related whit #120 

Regards.

**Comment by lingboz** [comment]
Hi, I also have this issue. 

In my browser all things work well however, when I tried both Android Emulator 7.1.1 and 7.0 they generate the same error.

I did not test on Android 5.0 but I will try tomorrow.

Ios simulator in Xcode is not working as well.

The error is very strange because everything worked well on device before.

Just follow this thread if you guys have the same problem

**Comment by wilkovanhoek** [comment]
Same issue here as well. 

Everything is fine on Chrome/Opera and Android 6.0.

 In my case it breaks on Firefox (version 54 - Ubuntu) and CyanogenMod 12.1 (Android 5.1.1). The Android 5.1.1 thing is strange as @fernandoarevalo seems to have no Problem on it, maybe its duet to CyanogenMod.

@lingboz and @fernandoarevalo: could you test if everything works for you on Firefox (regular ionic serve)?

**Comment by lingboz** [comment]
Hi @wilkovanhoek 

I tested on Firefox, the error is the same with simulators (as the following picture).
![image](https://user-images.githubusercontent.com/8528045/29316109-ff33c672-819c-11e7-8d43-dbf1b0c43f29.png)

Moreover I would like to attach my device error inspected by Chrome as follows, I am using Android simulator 7.1.1 from Android studio

![image](https://user-images.githubusercontent.com/8528045/29316164-34dad72a-819d-11e7-9a16-cea8d8e982ea.png)


They are actually the same errors I guess. 

I guess it is not due to the update of Meteor 1.5.1 because the built-in Meteor cordova support is working well and we have not seen many issue reports there.

**Comment by hwonda** [comment]
I suspect this issue has to do with Ionic App Script 2.1.3, has anyone tried a lower version? I'm away from my project now so I cannot give do this now.

**Comment by lingboz** [comment]
Guys do you think there is something wrong with Ionic 3?

I saw this error when I updated to Meteor 1.5.1 but my colleague is also using Meteor always with Meteor's built-in cordova support and his mobile app works very well with no issues.

I also noticed there is some changes between the generated "meteor-client" files from different versions of Meteor.

**Comment by lingboz** [comment]
@hwanda, I will try downgrade app script to lower versions

**Comment by pkitatta** [comment]
Hi, I have the same issue. The interesting thing is that the app was loading about two weeks ago and then one day this error happened. From that day it has persisted. I have tried everything.

**Comment by fernandoarevalo** [comment]
@wilkovanhoek, I tried to run the ionic serve in the Firefox and it generates the same error. Also, I tested in android simulator  whit 5.0.0 versions  but no working, it seems that works fine in devices whit higher versions to Android 5.0.0

**Comment by lingboz** [comment]
Hi @pkitatta  @hwonda  @wilkovanhoek  @fernandoarevalo 

I had an interesting test.

I had an code archive several weeks ago and I copied the old "meteor-client.js" to my current project. The error disappeared and my code worked on mobile platforms.

I double checked the differences between the two "meteor-client.js" files and I found a lot of differences.

I don't know if it is because I updated Meteor version to 1.5.1 but, when I run "meteor-client:bundle" to generate a new "meteor-client.js", everything breaks again.

This is absolutely not a good solution because we might lose support forever when we update things.

Have you found any clues how this error is caused?

**Comment by pkitatta** [comment]
@lingboz I also suspect it could be a meteor issue. It could be the upgrade.

**Comment by fernandoarevalo** [comment]
Hi @lingboz, i did a test whit meteor-client.js old version in iOS device 10.3.1 version y it works fine. The problem seems is meteor-client.js generated whit the latest meteor version

**Comment by fernandoarevalo** [comment]
@lingboz, I just added generated file by a meteor old version (backup file since february) in node_modules path and tested on the iOS device, I think the problem is when running "meteor client: bundle" that looks for the meteor latest version and not a specific version or the latest meteor-client-bundler module version (current 0.2.1)

**Comment by lingboz** [comment]
Hi @fernandoarevalo 
Hi yes, when you call that script it checks Meteor's update and will run the latest version.

But I guess this might not be the answer we are looking for, because we are going to update it in the long run. Further errors may occur

**Comment by lingboz** [comment]
@wilkovanhoek  hmm, good to know that 1.5 is working

**Comment by fernandoarevalo** [comment]
Hi @wilkovanhoek,

* What do you mean "downgrade my Meteor version to 1.5", you refer the global meteor version or project meteor version?
* How do you do to force the generation the meteor-client file with Meteor 1.5 version and not the latest?

**Comment by wilkovanhoek** [comment]
@fernandoarevalo 
- yes, I reinstalled my global Meteor to version 1.5
- I did not force it. I first thought the bundler would just go with the global Meteor version, which it kind of did the first time I bundled it. When bundling a second time it downloaded the new version anyway. Testing it today showed that the bundler only upgrades if the new version of meteor is know. This means you have to actively call meteor yourself (which I did between the two bundling processes yesterday by starting the meteor server locally). So this is not even a temporary fix.

**Comment by sxxymzy** [comment]
Same issue here, I tried downgrade to version 1.5, another issue "TypeError: Cannot read property 'get' of undefined" pop up so I have to upgrade back to 1.5.1.

**Comment by lingboz** [comment]
Anyone double checked webpack and meteor-client-bundler to see if they have problems?

**Comment by sxxymzy** [comment]
Hi guys, I've got it working by removing the following two dependencies in meteor-client.js.
`... _require('core-js/modules/es6.typed.uint8-array'); // line 17020 _require('core-js/modules/es6.typed.uint32-array'); // line 17021 ...`
I didn't do much tests to ensure its safety, but I think it might be safe if you don't use TypeArray in code. Hope there will be updates soon.

**Comment by pkitatta** [comment]
Hi guys, I have an update on the issue. @fernandoarevalo  was right to suspect the bundler.

I have realised it's not a meteor version issue for three reasons:

1. When I was going through my backedup projects I realised that 2 of the working projects I backed up early this month had meteor 1.5.1.

2. Looking at the meteor-client.js file from early this month and the one generated of late there is a difference in the code.

3. When I import the old generated file from early this month into the new project, the app runs fine.

I suspect it is a bug in the new generated file. We might need to find the author @DAB0mB for this.
Hi guys, I have an update on the issue. @fernandoarevalo  was right to suspect the bundler.

I have realised it's not a meteor version issue for three reasons:

1. When I was going through my backedup projects I realised that 2 of the working projects I backed up early this month had meteor 1.5.1.

2. Looking at the meteor-client.js file from early this month and the one generated of late there is a difference in the code.

3. When I import the old generated file from early this month into the new project, the app runs fine.

I suspect it is a bug in the new generated file. We might need to find the author @DAB0mB for this.

**Comment by pkitatta** [comment]
Hi guys, I have an update on the issue. @fernandoarevalo  was right to suspect the bundler.

I have realised it's not a meteor version issue for three reasons:

1. When I was going through my backedup projects I realised that 2 of the working projects I backed up early this month had meteor 1.5.1.

2. Looking at the meteor-client.js file from early this month and the one generated of late there is a difference in the code.

3. When I import the old generated file from early this month into the new project, the app runs fine.

I suspect it is a bug in the new generated file. We might need to find the author @DAB0mB for this.
Hi guys, I have an update on the issue. @fernandoarevalo  was right to suspect the bundler.

I have realised it's not a meteor version issue for three reasons:

1. When I was going through my backedup projects I realised that 2 of the working projects I backed up early this month had meteor 1.5.1.

2. Looking at the meteor-client.js file from early this month and the one generated of late there is a difference in the code.

3. When I import the old generated file from early this month into the new project, the app runs fine.

I suspect it is a bug in the new generated file. We might need to find the author @DAB0mB for this.

**Comment by wilkovanhoek** [comment]
Hi everyone,

I finally managed to find some time for this again. I found a working older version of meter-client.js with Meteor 1.5.1 as well on one of my systems. So the Meteor version is not the root cause. Following the solution from @sxxymzy, the issues seem to be deeper in the dependency trees.

Anyhow, version 1.5 fixes it for me right now. I decided to fork the meteor-client-bundler and add the possibility to specify the meteor version ([wilkovanhoek/meteor-client-bundler](https://github.com/wilkovanhoek/meteor-client-bundler)). This is not a permanent solution but it works for me for now. Also, I think it is a suitable addition to the meteor-client-bundler. I proposed to include the changes in the original project.

**Comment by pkitatta** [comment]
Hi @wilkovanhoek, so does it it mean that the bundler will generate a working client file.

Looking at @sxxynxy solution, I found those same lines in the older client file which has no problem, so are they really the problem?

**Comment by wilkovanhoek** [comment]
Hi @pkitatta, 
it does create a running file for me. I also decided to go back to Meteor 1.5 on the server side, to be sure they are aligned. 

I also tried to look into the dependency a bit closer, but could not really find the source.

**Comment by pkitatta** [comment]
I have versions 1.5 and and 1.5.1 installed on different projects. Bundling with 1.5 was giving me the new problematic file. So are you saying we should reinstall the meteor-client-bundle globally?
Sorry for my slow understanding.

**Comment by wilkovanhoek** [comment]
As far as I could trace it, meteor-client-bundle will bundle with 1.5.1 no matter what your project release file says. It executes a regular "meteor create" command to create a temporary project. This will use the most recent stable meteor release (currently 1.5.1). That is the reason why I added the possibility to specify the meteor release for the meteor-client-bundler.

To use this, you would have to install my version of meteor-client-bundler (for me it only worked globally, maybe I missed something). You can do this by executing:

`npm i -g git+https://git@github.com/wilkovanhoek/meteor-client-bundler`

after the installation check if it is version 0.2.2 now

`meteor-client -V`

now try to build the bundle with version 1.5 by adding "release 1.5" to the bundle command like so:

`meteor-client bundle --release 1.5`

you still can use all other parameters to include a config file or whatever you included/condigured before.

This worked for me even without downgrading the server side Meteor version. If it does not work for you, you can go back to the npm meteor-client-bundler package:

`npm i -g meteor-client-bundler`

Maybe I should have been clearer on what I did. Anyhow, I hope this makes the process clearer. Please let us know if it works for you too.
Cheers!

**Comment by pkitatta** [comment]
O.K now I get this error:

![image](https://user-images.githubusercontent.com/17586059/29531913-97fc11cc-865f-11e7-96f4-1b335b4586ad.png)

**Comment by pkitatta** [comment]
![image](https://user-images.githubusercontent.com/17586059/29532172-a647d7a6-8660-11e7-8306-7090577be295.png)

So is this how your meteor-client looks now?

**Comment by wilkovanhoek** [comment]
My meteor-client looks different. I don't have the 'Disable hot-code-push' lines. It looks like this.

```
__meteor_runtime_config__ = {
  "meteorEnv": {},
  "DDP_DEFAULT_CONNECTION_URL": "http://localhost:3000"
};

//////////////////////////////////////////////////////////////////////////
//                                                                      //
// This is a generated file. You can view the original                  //
...
```

I don't know, but maybe there is something wrong with the way that meteor-client is included. See ["Package is not defined"](https://github.com/Urigo/meteor-client-bundler/issues/11). Did you use the current master branch of the Tutorial?

**Comment by pkitatta** [comment]
Yes, that how the original looks like. But when I use your bundler then I get that client file with only 12 lines.
I have gone back to the original for now(0.2.1). Also "Disable hot-code-push' lines" are there in the original(both the working and non working client files), they are usually the last pieces of code.

**Comment by wilkovanhoek** [comment]
Oh, now I understand. that is the whole meteor-client :-( Well, it's a pity it does not work for you. What is the exact bundle command/output that you have used/got?

**Comment by pkitatta** [comment]
I followed your instructions above. First the bundler changed to 0.2.2 and then after bundling with the `--release 1.5` flag I got a client file with 12 lines as shown. I did this with meteor version 1.5. I reverted back to 0.2.1 and the rest of the code came back.

**Comment by wilkovanhoek** [comment]
Hmmm, that's bad. Sorry, but it seems I can't help you there.

**Comment by carlos-olivera** [comment]
Same problem here, only did work with se hack of @sxxymzy

**Comment by lingboz** [comment]
Hi guys, there is a new release from Meteor.
Meteor has 1.5.2 ready. They claimed they fixed some issues about Node.js V8, and supported Cordova 7.0.
What version of Cordova are you using?

https://blog.meteor.com/announcing-meteor-1-5-2-105b53e0debc
Have you guys tried anything about the new release?

**Comment by darkbasic** [comment]
Didn't try Meteor 1.5.2, but I rebased the whole tutorial to 1.6.0beta: https://github.com/darkbasic/Ionic2CLI-Meteor-WhatsApp/
You can have a look if you want, but please don't report bugs for 1.6.0beta because I don't plan to support it until it gets released.

**Comment by lingboz** [comment]
Hi @darkbasic 
That is great,
I will definitely try your repo.
I will also try the Meteor 1.5.2.

**Comment by darkbasic** [comment]
Please note that you will need an unreleased `meteor-client-bundler` in order to use `1.6beta`, because you will have to pass the `--release` parameter:
```
meteor-client bundle -s api --release 1.6-beta.26
```
You can find the patch in a [PR](https://github.com/Urigo/meteor-client-bundler/pull/42).

**Comment by airstep** [comment]
Any news? Tried with 1.6-rc2 still not load application. And no errors from log in XCode

**Comment by airstep** [comment]
Testing with 1.6-beta.26 and it also doesn't work. 

Using this: `meteor-client bundle -s api --release 1.6-beta.26`

I've got error like on screenshot.
![screenshot](https://user-images.githubusercontent.com/5022948/31122298-e75ffc50-a843-11e7-82ed-5a302154918d.png)

**Comment by lingboz** [comment]
@airstep  We are still investigating.

**Comment by airstep** [comment]
I must say that it is work with Simulate iOS in browser. But still doesn't in simulator\emulator\real device.

**Comment by IvanLjubicic** [comment]
Hi guys.

Any news regarding this? I encountered the same problem like @airstep showed on the screenshot.

Thanks.

**Comment by darkbasic** [comment]
Let's track it here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/124#issuecomment-331118105
