### ISSUE TITLE
Angular-Meteor "Advanced Tutorial" 404

### ISSUE THREAD

**Issue by pugna23** [Urigo/Ionic2CLI-Meteor-WhatsApp#131]
Hi!

I found that some Meteor Tutorials (For example: https://www.meteor.com/tutorials/angular/filtering-collections) are referencing to “[Angular-meteor Advanced Tutorial](https://angular-meteor.com/tutorial/step_12)”. This link is broken... I think that it is obsolet…

Do you still have an advanced tutorials section in angular-meteor site?

I opened [this issue](https://github.com/meteor/tutorials/issues/141) trying to solve the issue

Sorry if this is not the place to post it.

Thank you 😊

**Comment by darkbasic** [comment]
I followed your link and it seems to be fixed thanks to your PR. Thanks.
