### ISSUE TITLE
npm ERR! git submodule

### ISSUE THREAD

**Issue by dmacasero** [Urigo/Ionic2CLI-Meteor-WhatsApp#138]
![image](https://user-images.githubusercontent.com/14083720/31730811-af1e963e-b465-11e7-8211-2275bb9d11ad.png)

**Comment by darkbasic** [comment]
We don't use submodules at all... Are you doing a fresh checkout or are you trying to update an older version of the repo?

**Comment by dmacasero** [comment]
Yup I downloaded the repo yesterday to try and test the application before building my own. Then I run ionic serve? Maybe I had skipped some processes?

**Comment by darkbasic** [comment]
git clone https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp.git
cd Ionic2CLI-Meteor-WhatsApp
npm install
npm run meteor-client:bundle
npm run api
npm run ionic:serve
