### ISSUE TITLE
Not able to run the App

### ISSUE THREAD

**Issue by nikhilcfc** [Urigo/Ionic2CLI-Meteor-WhatsApp#15]
I deployed the Updated App on Ionic View, the Phone Number page appears, when I give the Phone Number and press Done, it does not do anything.

**Comment by dotansimha** [comment]
Do you have any errors in the log?

**Comment by nikhilcfc** [comment]
No errors as such.
Also I was trying to build the app from the scratch, after I add ngOnInit function in Step 3.15, the initial Page load does not happen. No errors in the log.

**Comment by nikhilcfc** [comment]
More Info..When Following step by step tutorials. Inside the api directory when I run these 2 commands ::
1) meteor npm install --save meteor-node-stubs zone.js meteor-rxjs meteor-typings
2) meteor npm install --save moment @types/moment

I get this : 
UNMET PEER DEPENDENCY rxjs@^5.0.0-beta.12
WARN meteor-rxjs@0.4.3 requires a peer of rxjs@^5.0.0-beta.12 but none was installed

**Comment by nikhilcfc** [comment]
I can see that this function is not working and pulling any chats.

 ngOnInit() {
    this.chats = Chats
      .find({})
      .mergeMap((chats: Chat[]) =>
        Observable.combineLatest(
          ...chats.map((chat: Chat) =>
            Messages
              .find({chatId: chat._id})
              .startWith(null)
              .map(messages => {
                if (messages) chat.lastMessage = messages[0];
                return chat;
              })
          )
        )
      ).zone();
  }

**Comment by nikhilcfc** [comment]
Any updates on this ? I recloned the application and when I run ionic serve, it just does not want to move ahead from the login page, regardless of the phone number I give.

**Comment by metecantimur** [comment]
Did you run **meteor** when you run **ionic serve**?

**Comment by dotansimha** [comment]
@nikhilcfc I fixed a lot of issues in the last days, please try again and re-open if you still have issues.
