### ISSUE TITLE
The modified webpack.config.js doesn't work with the latest @ionic/app-scripts@0.0.43

### ISSUE THREAD

**Issue by yuyinitos** [Urigo/Ionic2CLI-Meteor-WhatsApp#19]
The webpack.config.js file of @ionic/app-scripts@0.0.43 has been changed significantly by Ionic and I can't make it work with this repo. I reverted back to @ionic/app-scripts@0.0.39 (with the latest modification from issue #18) and the build process worked fine again.

**Comment by dotansimha** [comment]
That's correct, Ionic 2 still supports Webpack build only in it's beta version of the app-scripts. 
For more information, see [this](https://forum.ionicframework.com/t/help-us-test-webpack-support-in-ionic-2-app-scripts/67507). 

At the moment, we still must use `@ionic/app-scripts@beta`.
