### ISSUE TITLE
Connect to deployed meteor server

### ISSUE THREAD

**Issue by adoultremont** [Urigo/Ionic2CLI-Meteor-WhatsApp#4]
Hi,

Thanks for this great tutorial.
Could you explain a little more in details how to connect to the deployed meteor server?

I have created a global object at the top of app.ts 

`var __meteor_runtime_config__ = {
  DDP_DEFAULT_CONNECTION_URL: 'api.server.com'
};`

but I cannot establish connection ERR_CONNECTION_REFUSED, tried also 

`__meteor_runtime_config__ = {};
__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = 'api.server.com';`

but then I get a typescript error.

I could not a find a clear explanation elsewhere.

Many thanks,

Alexis

**Comment by themastersoda** [comment]
I have stumbled in this part as well. If someone could show an example of exactly where and how they set their server url it would help a lot.
I've tried to set it in my application www/index.html file like so:
<script>__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = 'my.url:3000';</script>
<script>__meteor_runtime_config__ = {DDP_DEFAULT_CONNECTION_URL: 'my.url:3000'};</script>

None of this has worked. Same with setting it in app.ts. To work around this issue i ended up editing libraries themselves, which works, but a clean, correct solution would be highly appreciated.

**Comment by mmazloum** [comment]
If found something just found something here https://forums.meteor.com/t/develop-and-deploy-server-side-independently-from-client-side-ionic-meteor/21810/10

but couldn't figure out exactly how to make it work

**Comment by triasrahman** [comment]
any solution for this?

**Comment by mmazloum** [comment]
Something that works fine for me : 
is to change the url deep inside meter-client-side.min.js inside the node module.

**Comment by themastersoda** [comment]
Yes, i said that ir works already, but im looking for a cleaner solution

**Comment by triasrahman** [comment]
really? editing inside `meteor-client-side.bundle.min.js` isn't proper solution.

**Comment by themastersoda** [comment]
It isnt, but It does the job while there's no better way

**Comment by navi8602** [comment]
I use a variant of this lesson, and in the assembly of my all works
[https://github.com/Muffasa/ionic2-meteor-starter]

**Comment by AwsmOli** [comment]
Here is my dirty fix: 

i found the method that defaults to localhost:300 in `meteor-client-side.bundle.min.js` just search for `localhost:3000` to find it ;)
```
(function() {
  var _ = Package['underscore']._;
  var config = this.__meteor_runtime_config__ || {};
  __meteor_runtime_config__ = _.defaults({}, config, {
    meteorEnv: {},
    DDP_DEFAULT_CONNECTION_URL: 'http://localhost:3000'
  });
}).call(this);
```

and added the global variable **`__meteor_runtime_config__`** (the one we should set in index) to the `_.defaults` function:

```
(function() {
  var _ = Package['underscore']._;
  var config = this.__meteor_runtime_config__ || {};
  __meteor_runtime_config__ = _.defaults({}, __meteor_runtime_config__, config, {
    meteorEnv: {},
    DDP_DEFAULT_CONNECTION_URL: 'http://localhost:3000'
  });
}).call(this);
```

and now setting the runtimeconfig in index works :) 

its still not optimal as every time you update meteor-client-side or someone new on your team checks out the codebase and runs npm install will have to make that change :/

**Comment by dotansimha** [comment]
You need to override it as described in `meteor-client-side` instructions. 
Create `__meteor_runtime_config__` on you global scope as object with `DDP_DEFAULT_CONNECTION_URL`:
```ts
__meteor_runtime_config__ = {
     DDP_DEFAULT_CONNECTION_URL: "..."
}
```
Add this before loading `meteor-client-side` in the `main.dev.ts` file.

**Comment by themastersoda** [comment]
Did not work, here's how my main.dev.ts looks:

```
var __meteor_runtime_config__ = {
  DDP_DEFAULT_CONNECTION_URL: "http://123.123.123.123"
}

import 'meteor-client-side';
import 'accounts-base-client-side';
import 'accounts-password-client-side';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';

Meteor.startup(() => {
  platformBrowserDynamic().bootstrapModule(AppModule);
  Tracker.autorun(() => {
    if (Meteor.loggingIn()) return;
  });
});
```

Without using var it simply doesn't compile, with var it just points out that its an unused variable, but it still tries to connect to localhost.

```
polyfills.js:1 GET http://localhost:3000/sockjs/info?cb=b4746trvbm net::ERR_CONNECTION_REFUSED
```

**Comment by dotansimha** [comment]
Without `var`, it should be on the global scope, so add `global.` or without `var`.

**Comment by themastersoda** [comment]
without var it does not pass the typescript compiler `Cannot find name '__meteor_runtime_config__'`, with global it's the same `Cannot find name 'global'. L1:  global.__meteor_runtime_config__`.

**Comment by dotansimha** [comment]
Try this:
```ts
global['__meteor_runtime_config__'] = {
  DDP_DEFAULT_CONNECTION_URL: "http://123.123.123.123"
}
```

**Comment by themastersoda** [comment]
same `Cannot find name 'global'. L1:  global['__meteor_runtime_co...`. Global is not defined by default, so none of those are going to work i guess.

**Comment by dotansimha** [comment]
Yeah my bad, it's the client side, so it's must be `window`: 
```ts
window['__meteor_runtime_config__'] = {
  DDP_DEFAULT_CONNECTION_URL: "http://123.123.123.123"
}
```

**Comment by themastersoda** [comment]
Well this time it compiles without problems, but the package still tries to connect to localhost:
```
polyfills.js:1 GET http://localhost:3000/sockjs/info?cb=mz8jm6jq01 net::ERR_CONNECTION_REFUSED
```

**Comment by themastersoda** [comment]
If I move the assignment below `import 'meteor-client-side';`, it get's set, but connection is already being initialized to localhost, so my guess is that the package is not correctly checking for existing variable before setting it's default values

**Comment by dotansimha** [comment]
@idanwe any idea? with the recent `meteor-client-side` package, just noticed that Meteor overrides the global value:
```
  __meteor_runtime_config__ = _.defaults({}, config, {
    meteorEnv: {},
    DDP_DEFAULT_CONNECTION_URL: 'http://localhost:3000'
  });
```

**Comment by idanwe** [comment]
It is now fixed.

There was a problem with the context in the minified version.
idanwe/meteor-client-side#28

**Comment by themastersoda** [comment]
Can confirm, updating to meteor-client-side@1.3.5 and setting url via
```
window['__meteor_runtime_config__'] = {
  DDP_DEFAULT_CONNECTION_URL: "http://MY_SERVER_IP_HERE"
};
```
right before importing meteor-client-side in main.dev.ts is working fine

**Comment by msio777** [comment]
unfortunately it isn't working by me 
my main.dev.ts: 

```
window['__meteor_runtime_config__'] = {
    DDP_DEFAULT_CONNECTION_URL: "http://123.123.123.123"
};

import 'meteor-client-side';
import 'accounts-base-client-side';

import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

import {AppModule} from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule);

```

client is still connecting to localhost:3000

my enviroment:
```
"ionic-angular": "2.0.0-rc.3"

"@ionic/app-scripts": "0.0.45",
```

I appreciate any help 
thanks :)

**Comment by idanwe** [comment]
@msio777 can you confirm that meteor-client-side version is 1.3.5?

**Comment by msio777** [comment]
this is the package.json under meteor-client-side in my node_modules

```
{
  "_args": [
    [
      {
        "raw": "meteor-client-side@1.3.5",
        "scope": null,
        "escapedName": "meteor-client-side",
        "name": "meteor-client-side",
        "rawSpec": "1.3.5",
        "spec": "1.3.5",
        "type": "version"
      },
      "/XXXXXXXXXX"
    ]
  ],
  "_from": "meteor-client-side@1.3.5",
  "_id": "meteor-client-side@1.3.5",
  "_inCache": true,
  "_location": "/meteor-client-side",
  "_nodeVersion": "4.4.5",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/meteor-client-side-1.3.5.tgz_1480333295347_0.7963037898298353"
  },
  "_npmUser": {
    "name": "idanwe",
    "email": "idanwe2@gmail.com"
  },
  "_npmVersion": "2.15.5",
  "_phantomChildren": {},
  "_requested": {
    "raw": "meteor-client-side@1.3.5",
    "scope": null,
    "escapedName": "meteor-client-side",
    "name": "meteor-client-side",
    "rawSpec": "1.3.5",
    "spec": "1.3.5",
    "type": "version"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/meteor-client-side/-/meteor-client-side-1.3.5.tgz",
  "_shasum": "8887901037bdc29a7311601eb8f1117244e58d47",
  "_shrinkwrap": null,
  "_spec": "meteor-client-side@1.3.5",
  "_where": "/XXXXXXXXXXXXXXXXXXXXX",
  "author": {
    "name": "Idan Wender",
    "email": "idanwe2@gmail.com"
  },
  "bugs": {
    "url": "https://github.com/idanwe/meteor-client-side/issues"
  },
  "dependencies": {},
  "description": "Use Meteor's client side DDP protocol and Minimongo in a non Meteor project",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "shasum": "8887901037bdc29a7311601eb8f1117244e58d47",
    "tarball": "https://registry.npmjs.org/meteor-client-side/-/meteor-client-side-1.3.5.tgz"
  },
  "gitHead": "5306854312335fed38acf4fc805a66de70f06a87",
  "homepage": "https://github.com/idanwe/meteor-client-side#readme",
  "keywords": [
    "meteor",
    "ddp",
    "minimongo",
    "mongo",
    "client",
    "side"
  ],
  "license": "MIT",
  "main": "dist/meteor-client-side.bundle.min.js",
  "maintainers": [
    {
      "name": "domenukk",
      "email": "domeenukk@gmail.com"
    },
    {
      "name": "idanwe",
      "email": "idanwe2@gmail.com"
    }
  ],
  "name": "meteor-client-side",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/idanwe/meteor-client-side.git"
  },
  "scripts": {},
  "version": "1.3.5"
}

```

**Comment by metecantimur** [comment]
Please see #20

**Comment by rlaurente** [comment]
actually when you build the client app, you can add --url to specify where's your server.

npm run meteor-client:bundle --url="x.x.x.x:3000"

**Comment by rlaurente** [comment]
The most clean way is to add --url <ip>:<port> inside your package.json like this

"meteor-client:bundle": "meteor-client bundle -s api --url 192.168.x.x:3000"

and build the client: npm run meteor-client:bundle
