### ISSUE TITLE
Cannot find module "meteor-client"

### ISSUE THREAD

**Issue by msio777** [Urigo/Ionic2CLI-Meteor-WhatsApp#43]
I pulled right know the newest version but I got `Cannot find module "meteor-client"`
Did I miss something ?
thank you 
Best Regards
Michal

**Comment by DAB0mB** [comment]
@msio777 You need to install `meteor-client-bundler`, run `npm run meteor-client:bundle`, and only then run `ionic serve`. The `meteor-client-bundler` bundles the client required to operate with the `Meteor` server. More details can be found here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/manuals/views/step4.md#preparing-the-meteor-client

**Comment by msio777** [comment]
Thanks a lot. I didn't see that before in the tutorial :)

**Comment by DAB0mB** [comment]
No problem. It's a new package we decided to develop so we can use Atmosphere packages.
