### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 48.

### ISSUE THREAD

**Issue by msio777** [Urigo/Ionic2CLI-Meteor-WhatsApp#44]
Hi,
If I run `npm run api` , I got this error on meteor
`Error: Module version mismatch. Expected 46, got 48.`

Thanks
Beste Regards 
Michal

**Comment by DAB0mB** [comment]
Remove `sharp`:

    $ rm -rf node_modules/sharp

Install `sharp` using `Meteor`:

    $ meteor npm install sharp

**Not** like so:

    $ npm install sharp

Further explanation can be found here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/manuals/views/step12.md#server-side
Please tell me if it did the trick for you.

**Comment by msio777** [comment]
Thanks it works. I like the folder architecture you did but I think it would be little bit clearer if client and meteor have own node_modules it means probably 2 package.json files. I did it that way in my project but I did not share code between client and api. I have to say that some stuff would be better  if I could use in both
