### ISSUE TITLE
Error: TS2339:Property 'platform' does not exist on type 'NewLocationMessageComponent'

### ISSUE THREAD

**Issue by kilaka** [Urigo/Ionic2CLI-Meteor-WhatsApp#49]
Getting error on file location-message.ts line 47:
TS2339:Property 'platform' does not exist on type 'NewLocationMessageComponent'

In revision 610f50c (latest as of now) but on previous revisions as well.

Browser shows the error as well when navigating to http://localhost:8100/.

Hope I helped a bit.

**Comment by DAB0mB** [comment]
@kilaka Your'e right, I just fixed it. See https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/manuals/views/step11.md#added-srcpagesmessageslocation-messagets
