### ISSUE TITLE
angular 2 meteor 'whatsapp' clone is not working at step '4. Realtime Meteor Server ' -- 404 error with http://localhost:3000/sockjs/info.....

### ISSUE THREAD

**Issue by TarunKala** [Urigo/Ionic2CLI-Meteor-WhatsApp#63]
Hi,

 i have fallowed the steps as in https://angular-meteor.com/tutorials/whatsapp2/ionic/meteor-server-side.

but after setting up realtime meteor server with mongo DB data is not loading and,
Console shows the following error(which is continuously hitting): 

_

> Failed to load resource: the server responded with a status of 404 (Not Found)   http://localhost:3000/sockjs/info?cb=8gic9r08wc 

_

im running the ionic server on port 3000 which will be same for meteor(api)

Any idea whats the reason for this issue

![meteorbug](https://cloud.githubusercontent.com/assets/22730778/23105263/858fab62-f702-11e6-9db6-7cecd31b2cc8.png)

**Comment by gotu** [comment]
You should not run ionic-dev-server and meteor-chat-sever it on same port.

**Comment by pkitatta** [comment]
@TarunKala Did you solve this issue? I have the exact problem

**Comment by pkitatta** [comment]
I solved this by running the meteor server: api>$ meteor

This is not something you will find in the tutorial. For some reason I failed several times when I run: $ npm run api
