### ISSUE TITLE
Tutorial Step 2 needs update src/models.ts is missing

### ISSUE THREAD

**Issue by Blacktoviche** [Urigo/Ionic2CLI-Meteor-WhatsApp#64]
I was just following your tutorial and in step 2 you mentioned creating TypeScript Interfaces in src/models.ts but in you repository this file is missing

**Comment by gotu** [comment]
The models are moved in Step 3 of the tutorial. See:
>Now we'll have to move our models interfaces to the api dir so the server will have access to them as well:

>$ mv src/models.ts api/server/models.ts
>This requires us to update its reference in the declarations file as well:
