### ISSUE TITLE
@types/meteor deprecated?

### ISSUE THREAD

**Issue by gotu** [Urigo/Ionic2CLI-Meteor-WhatsApp#67]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/meteor

@types/meteor is announced as deprecated and meteor-typings should be used.

meteor-rxjs switched in last version https://github.com/Urigo/meteor-rxjs/blob/master/CHANGELOG.md#047-2016-12-21 switched from meteor-typings to @types/meteor and references it directly <reference types="@types/meteor" />

So what is currently the status here? The tutorial sais to install both meteor-typings and @types/meteor and to turn on typescript compiler option --skipLibCheck, but it does not explain what is going on here..

**Comment by gotu** [comment]
So to update this issue. As I see https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/meteor was updated now for Meteor 1.4 and the "deprecated" note was removed again..

Still why is there need for both in this tutorial, both meteor-typings and @types/meteor? 

Also with the last update of @types/meteor it raises this issue: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/51#issuecomment-286944255

**Comment by KeithGillette** [comment]
That URL produces a 404 error, @gotu. This one works but only goes through 1.3 and is deprecated:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types/meteor

However, I searched and found this one, which is updated for 1.4:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/354cec620daccfa0ad167ba046651fb5fef69e8a/types/meteor

I, too am confused by the inclusion of multiple Meteor typings. Any clarity emerging on who maintains up-to-date Meteor typings?

I developed [some for the `apollographql/meteor-integration` Atmosphere package](https://github.com/KeithGillette/Apollo-GraphQL-Meteor-Integration-Typings) but am [not sure where to submit them for use by others](https://github.com/apollographql/meteor-integration/issues/65).

**Comment by darkbasic** [comment]
Any clue on this?

**Comment by darkbasic** [comment]
Only `@types/meteor` is used in latest version of the tutorial. I'm closing.
