### ISSUE TITLE
Windows equivalent for ln -s ../node_modules

### ISSUE THREAD

**Issue by zettre** [Urigo/Ionic2CLI-Meteor-WhatsApp#68]
Hi, how to execute the equivalent command in windows cmd.

**Comment by IvanLjubicic** [comment]
You got complete explanation here

https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

mklink /D "C:\Link To Folder" "C:\Users\Name\Original Folder"

**Comment by zettre** [comment]
Thanks, but just one query, the 2nd option to mklink can be any name in this project for example if i am in api folder and i use the command as "mklink /D link  ..\node_modules" is it correct.
