### ISSUE TITLE
Example with accounts-password

### ISSUE THREAD

**Issue by naysumyat** [Urigo/Ionic2CLI-Meteor-WhatsApp#7]
Hi, 
   thank you so much for the tutorial. it would be so great if you could show me a way to use accounts-password or accounts-facebook  instead of accounts-phone .

**Comment by mariohmol** [comment]
Hi there! I'm trying the same.. i just cant make accounts-password to be imported into the project.. I install it using atmosphere.. i made a import on main.js... but meteor keep without password functionality.. could you fix it?

**Comment by mariohmol** [comment]
Here is a repo trying to making this to work

* https://github.com/mariohmol/ionic2-meteor-messenger

Still having a problem:

```
I can create a user, it shows on mongo, i can call the loginwithpassword, but the problem is that he always get wrong user. 
```

**Comment by mariohmol** [comment]
all solved..  with accounts-password and latest versions for ionic2 and angular2. There is a module that handles the accouns-password for frontend, here is a full example : https://github.com/mariohmol/ionic2-meteor-messenger-password

**Comment by dotansimha** [comment]
@mariohmol Thanks!
