### ISSUE TITLE
Typescript Error Duplicate identifier 'Status' in Step 4

### ISSUE THREAD

**Issue by happylrd** [Urigo/Ionic2CLI-Meteor-WhatsApp#78]
Hi, I met the error in Step4.

My env is as follows:
```
Ionic Framework: 2.3.0
Ionic App Scripts: 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 6.10.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```
I fixed the problem after removing `meteor-typings` in the root `tsconfig.json`, but I'm very confused about it, someone tell me why?

Any help or guidance would be much appreciated.

**Comment by himanshuMaheshwari2311** [comment]
You need to comment or delete some lines from node_modules/@types/meteor/index.d.ts

First (651 - 677)
/*
declare module DDP {
    interface DDPStatic {
        subscribe(name: string, ...rest: any[]): Meteor.SubscriptionHandle;
        call(method: string, ...parameters: any[]): void;
        apply(method: string, ...parameters: any[]): void;
        methods(IMeteorMethodsDictionary: any): any;
        status(): DDPStatus;
        reconnect(): void;
        disconnect(): void;
        onReconnect(): void;
    }

    function _allSubscriptionsReady(): boolean;

    type Status = 'connected' | 'connecting' | 'failed' | 'waiting' | 'offline';

    interface DDPStatus {
        connected: boolean;
        status: Status;
        retryCount: number;
        retryTime?: number;
        reason?: string;
    }

    function connect(url: string): DDPStatic;
}*/

Second(689 - 726):
/*declare module "meteor/ddp" {
    module DDP {
        interface DDPStatic {
            subscribe(name: string, ...rest: any[]): Meteor.SubscriptionHandle;
            call(method: string, ...parameters: any[]): void;
            apply(method: string, ...parameters: any[]): void;
            methods(IMeteorMethodsDictionary: any): any;
            status(): DDPStatus;
            reconnect(): void;
            disconnect(): void;
            onReconnect(): void;
        }

        function _allSubscriptionsReady(): boolean;

        type Status = 'connected' | 'connecting' | 'failed' | 'waiting' | 'offline';

        interface DDPStatus {
            connected: boolean;
            status: Status;
            retryCount: number;
            retryTime?: number;
            reason?: string;
        }

        function connect(url: string): DDPStatic;
    }

    module DDPCommon {
        interface MethodInvocation {
            new (options: {}): MethodInvocation;

            unblock(): void;

            setUserId(userId: number): void;
        }
    }
}*/

**Comment by fjms** [comment]
Remove "meteor-typings" from tsconfig.json

**Comment by happylrd** [comment]
This is a pretty good tutorial I've seen, I hope it will be better.

Before closing the issue, I will list some tips about learning the tutorial in windows.

`ln -s source target` can be replaced with `mklink /D source target` in *windows*.

Specific to this tutorial,
- `ln -s ../node_modules` -> `mklink /D .\node_modules ..\node_modules`,
- `ln -s ../src/declarations.d.ts` -> `mklink .\declarations.d.ts ..\src\declarations.d.ts`.

Look forward to updating this tutorial.
