### ISSUE TITLE
Cannot type anything in messages page

### ISSUE THREAD

**Issue by himanshuMaheshwari2311** [Urigo/Ionic2CLI-Meteor-WhatsApp#79]
![1](https://cloud.githubusercontent.com/assets/22850405/24446102/f003a30a-1489-11e7-9019-6f2ddcea8edf.png)

Can somebody please look at this. I am unable to resolve it.

**Comment by fjms** [comment]
Have you defined the function? In pages/messages/messages.ts
`  onInputKeypress({ keyCode }: KeyboardEvent): void {
    if (keyCode === 13) {
      this.sendTextMessage();
    }
  }`

**Comment by himanshuMaheshwari2311** [comment]
Yes

**Comment by himanshuMaheshwari2311** [comment]
Anyway Thanks I guess I resolved it.

**Comment by himanshuMaheshwari2311** [comment]
I am closing this issue

**Comment by fjms** [comment]
This is my code https://github.com/fjms/Ionic2CLI-Meteor-WhatsappClone/blob/master/src/pages/messages/messages.ts
Can you paste yours?
