### ISSUE TITLE
Angular CLI instructions?

### ISSUE THREAD

**Issue by KeithGillette** [Urigo/Ionic2CLI-Meteor-WhatsApp#82]
Step 1 of the live version of the [WhatsApp Clone with Meteor and Ionic 2 CLI tutorial on Angular-Meteor.com](https://angular-meteor.com/tutorials/whatsapp2/ionic/setup) mentions an Angular CLI configuration:

> If you are interested in the Angular CLI, the steps needed to use it with Meteor are almost indentical to the steps required by the Ionic CLI

I have successfully gotten the old Socially Angular-Meteor demo application to build using `meteor-client-bundler` and Angular CLI, but am having module resolution issues with Angular CLI:

`import { Accounts } from 'meteor/accounts-base';` generates:

```
Module not found: Error: Can't resolve 'meteor/accounts-base' 
```
with `ng serve` or `ng build`.

However, if I just leave off the import statement, the code executes, as I have installed, bundled, and elsewhere imported necessary Atmosphere package.

Are there Angular CLI configuration instructions for Angular-Meteor?

**Comment by krishnapsms** [comment]
Hi @KeithGillette How you integrated with Angular CLI, Am trying to integrate with it now can you please share your steps ?

**Comment by KeithGillette** [comment]
I am afraid that have not gotten a perfect setup with Angular CLI, @krishnapsms, though I do have the basics working for a project which only uses Meteor for a few things.

1. Create an Angular CLI project via `ng new`
2. Install and configure [`meteor-client-bundler`](https://github.com/Urigo/meteor-client-bundler/) (see my configuration in [this Issues thread](https://github.com/Urigo/meteor-client-bundler/issues/5#issuecomment-279803548))
3. Install `angular2-meteor-polyfills`, `@typings/meteor` and any other Meteor-related packages
4. Import `meteor-client` and `angular2-meteor-polyfills` as first lines in `main.ts`:
```typescript
import 'meteor-client';		// First load Meteor client Atmosphere packages bundled with `meteor-client-bundler`
import 'angular2-meteor-polyfills';		// Next load needed Meteor and Angular shims prior to other Angular imports
```
5. Update `typings.d.ts` to make Meteor typings global:
```typescript
/// <reference path="../node_modules/@types/meteor/index.d.ts" />
```
This works for my current minimal use of Meteor on the client, though suffers from the following shortcomings:
1. Meteor TypeScript typings may be incomplete depending on what packages you're calling. You may have to create your own global typings and add them directly or by reference path to `typings.d.ts`.
2. Per [my initial post in this issue thread](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/82#issue-219680589), import statements for Atmosphere packages produce Angular CLI build errors, as the packages are bundled in `meteor-client` instead of being loaded by Webpack. If you were to perform an `ng eject` I think you could apply the [`webpack.config` changes noted in the WhatsApp Clone tutorial](https://angular-meteor.com/tutorials/whatsapp2/ionic/setup) to overcome this issue. For now, as noted in my first post, I just omit the import statements and rely on global typings to keep TypeScript happy.
3. The biggest problem is that you cannot use any Atmosphere packages which have dependencies on npm packages, as detailed in [this `meteor-client-bundler` thread](https://github.com/Urigo/meteor-client-bundler/issues/18).

Let me know if you have more questions or come up with solutions to any of these open issues. Thanks!

**Comment by krishnapsms** [comment]
Thanks @KeithGillette I will try and update you with configurations.

**Comment by krishnapsms** [comment]
Hi @KeithGillette Did you face the following issue after setting up everything and try to run ng serve
 `Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (E:\..\..\AngMCB\node_modules\typescript\lib\typescript.js:15457:109)`

**Comment by KeithGillette** [comment]
That error sounds familiar, @krishnapsms, but I don't think it's unique to Angular-Meteor. Rather, I think some entry in your `.angular-cli.json` configuration is referencing a non-existent file or directory.

**Comment by xriu** [comment]
For me is happening with the same error, but if you write a console.log(fileName) inside createSourceFile appears a non-existent file. 

Trace
```
.../api/node_modules/meteor-rxjs/dist/utils.d.ts
.../api/node_modules/meteor-typings/1.2/browser.d.ts
.../api/node_modules/meteor-typings/1.2/meteor.d.ts <= non-existent file
.../node_modules/typescript/lib/typescript.js:15458
            var sourceFile = new SourceFileConstructor(265 /* SourceFile */, /*pos*/ 0, /* end */ sourceText.length);
                                                                                                            ^

TypeError: Cannot read property 'length' of undefined
    at createSourceFile (.../node_modules/typescript/lib/typescript.js:15458:109)
```
.angular-cli.json
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "demo",
    "ejected": true
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {
    }
  }
}
```
tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": ".",
    "paths": {
      "api/*": ["./api/server/*"]
    },
    "sourceMap": true,
    "target": "es5",
    "skipLibCheck": true,
    "stripInternal": true,
    "noImplicitAny": false,
    "types": [
      "meteor-typings",
      "@types/underscore"
    ],
    "declaration": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "include": [
    "src/**/*.ts",
    "api/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "api/node_modules",
    "api"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by jgfet** [comment]
For me it was a missing src/test.ts

**Comment by darkbasic** [comment]
I made a small [AngularCLI+Meteor-client-bundler tutorial](https://github.com/darkbasic/angularcli-meteor) where I ported most of the content from the first 4 chapters of the IonicCLI tutorial. I will leave this open until we will get an angular-cli version of this tutorial.

**Comment by KeithGillette** [comment]
Thanks, @darkbasic! Does your ejected Angular CLI project configuration allow use of Atmosphere packages with npm package dependencies in the client?

**Comment by darkbasic** [comment]
I didn't test anything beyond a basic app, but it should work I think. Please test it and let me know.

**Comment by darkbasic** [comment]
I'm closing since I already made an AngularCLI + Meteor example: https://github.com/darkbasic/angularcli-meteor
I also made another example which uses Ionic 3 with the Angular CLI: https://github.com/darkbasic/angularcli-graphql

I'm also linking the other issue on meteor-client-bundler:
https://github.com/Urigo/meteor-client-bundler/issues/33
