### ISSUE TITLE
Lazy-loading messages correct?

### ISSUE THREAD

**Issue by stefanholzapfel** [Urigo/Ionic2CLI-Meteor-WhatsApp#84]
In step 10.3 you implement the countMessages method.

But since it runs on the server only (because it is placed in a \server folder), won't it always deliver the FULL count of ALL messages in the collection (and not only the relevant ones in the current chat)? 

If I get it right, only the publication is limited by an id parameter, but if we directly access the collection on the server, there are no limiting parameters?

Thanks for enlightenment ;-)

**Comment by stefanholzapfel** [comment]
Ok I think I partly got it. Since the local (client-side) Messages collection gathers all the messages from different chats, the count MAY add up to the total count of all messages in all chats.

But isn't it very unlikely that that ever happens? Since in a real environment there will be tons of chats (and therefore messages) in which one specific user will never participate? So the messageCount in the client-side database will never be reached?

**Comment by puba3r** [comment]
I noticed this a while ago. I fixed it by passing the chatId.

`  countMessages(chatId:string): number {
    return Messages.collection.find({chatId: chatId}).count();
  },`

**Comment by stefanholzapfel** [comment]
But that won't solve the issue.

When you have let's say 200 messages in your local database from different chats and you now open another one with e.g. 60 messages, you can't load anymore than the initial 30, because the observer completes due to the fact that it has more items in the local database than in this chat....

**Comment by stefanholzapfel** [comment]
Ahh, but you could also filter the local database within the observable, I guess thats what you did? ;-)

**Comment by stefanholzapfel** [comment]
That still has flaws...

E.g. when you close a chat an reopen it, the batchCounter is reset to 1....means if you are already having loads of messages in your client-side minimongo, you will have to scroll up and down several times (until the batchCounter * 10 is greater than the amount of messages in your minimongo) until you get older entries....

**Comment by stefanholzapfel** [comment]
Ok, I have solved it by just never disconnecting from the scroller and always check if there are more items in the subscribeMessages like that:

```
    // Subscribes to the relevant set of messages
    subscribeMessages(): void {
      // A custom offset to be used to re-adjust the scrolling position once
      // new dataset is fetched
      this.scrollOffset = this.scroller.scrollHeight;

      MeteorObservable.call('countMessages', this.selectedChat._id).subscribe((messagesCount: number) => {
          if (messagesCount > this.messagesCounter) {
              // A flag which indicates if there's a subscription in process
              this.loadingMessages = true;
              this.messagesCounter += 30;
              MeteorObservable.subscribe('messages',
                this.selectedChat._id,
                this.messagesCounter
              ).subscribe(() => {
                // Keep tracking changes in the dataset and re-render the view
                if (!this.messagesComputation) {
                  this.messagesComputation = this.autorunMessages();
                }

                // Allow incoming subscription requests
                this.loadingMessages = false;
              });
          }
      });
    }
```
