### ISSUE TITLE
Login with facebook from ionic 2 external client to meteor

### ISSUE THREAD

**Issue by ingleo** [Urigo/Ionic2CLI-Meteor-WhatsApp#92]
Hi,

I'm trying to login with facebook from the ionic application client, but when I execute the methods Meteor.loginWithFacebook... the response show this url (from device chrome inspect) and screen:

http://localhost:3000/oauth/facebook?close&code=AQAC8K-XaIIBjNlGapdPDKwE4iFl2ntxfVA4D4MEeAe4VjotFvRZ0XrNZ9ew8F5vD8Btp74latz58yfmq9ZplNrbIm9W72ykZkbz-H0lou06nfbVfBNPmw425n9ktpnWwR2IPtufeqs3e-5nF9iKMU_UvutdPaENxcc7g4l9Faw2SUoxwY4YhSMJdNAvLw_9D5ZYg2pEMlLbTRC8pkpfaf8_f883KTZ4rSRdjyIyUdT4WKZcRem-2dka7FV74f03bY3mlzt_rOpzGcH1Shts3oillDxQrD2oZsSsMmTpHZ5eRdlDeM4tDuWr_wG6cQ_vP3GGwlavYhP42QltWg2_7Pn4&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiI0aV9kdE54Ni1GSW9ncF9uOG5aM3liMDZuVzZQX3N6WG9qcXNOelBHbURvIiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D#=_

![seleccion_064](https://cloud.githubusercontent.com/assets/10843115/25727106/06ccfbc0-30ed-11e7-8069-c46be061fbfa.png)

And doesn't return to the app screen.

I posted a related issue in Urigo/angular-meteor#1567, still no solution (open)

If I put loginStyle: 'redirect'

```javascript
loginWithFacebook() {
        Meteor.loginWithFacebook({ requestPermissions: ['public_profile', 'email'], loginStyle: 'redirect' }, (err) => {

            this.zone.run(() => {
                if (err) {
                    this.error = err;
                } else {
                    console.log('done');
                }
            });
        });
    }
```
The app redirects to the server ip (http://localhost:3000).

I found this issue #11 (closed), in the message thread @dotansimha referenced this solution https://github.com/mixersoft/accounts-facebook-client-side; actually this is not supported for the latest meteor version and facebook package, replaced by facebook-oauth.

Has anyone a solution please?
Regards.

**Comment by darkbasic** [comment]
Please have a look at my latest post here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/40

**Comment by ingleo** [comment]
I looked and tried the recomendation of @darkbasic  in #40 using btafel:accounts-facebook-cordova package that works with cordova-plugin-facebook4 plugin, I did this steps.

1. Remove accounts-facebook package (because it creates conflict with btafel:accounts-facebook-cordova)
2. Add btafel:accounts-facebook-cordova and facebook-oauth(this one is removed with accounts-facebook)
3. Add facebook settings to settings.json file (according to  btafel:accounts-facebook-cordova documentation)
4. Add facebook-oauth and btafel:accounts-facebook-cordova in import object of meteor-client.config.json (according to Urigo/meteor-client-bundler)
```javascript
{
  "runtime": {
//lines skipped
  },
  "import": [
    "meteor-base",
    "accounts-base",
    "accounts-password",
    "service-configuration",
    "underscore",
    "meteor",
    "btafel:accounts-facebook-cordova",
    "facebook-oauth"
    //lines skipped
    ],
    "export": {
    "ddp": ["DDP"],
    "meteor": ["Meteor"],
    "mongo": ["Mongo"],
    "tracker": ["Tracker"],
    "underscore": ["_"],
    "accounts-base": ["Accounts"]
  }
}
```
5. In my ionic component...
```javascript
 loginWithFacebook() {
        Meteor.loginWithFacebook({ requestPermissions: ['public_profile', 'email'] }, (err) => {
            this.zone.run(() => {
                if (err) {
                    this.error = err;
                } else {
                    //lines skipped
                }
            });
        });
    }
```
6. Finally deploy the app in android and ios devices and getting the same error after login with the facebook popup.

![seleccion_064](https://cloud.githubusercontent.com/assets/10843115/25776147/f6b6ea8a-327b-11e7-8200-8aadd1f27740.png)

Inspecting on device chrome inspect, I found this object...
![seleccion_066](https://cloud.githubusercontent.com/assets/10843115/25776155/52b1777e-327c-11e7-8195-359b84d4e0cc.png)

I'm really stucked, I hope that  anybody can help me.

**Comment by darkbasic** [comment]
From your screenshot it seems you are trying to use the Browser Facebook API instead of the Android SDK Facebook API (```btafel:accounts-facebook-cordova``` can use both): it won't work on Cordova because the app will run locally with no domain.
You need to use the Android SDK Facebook API, which ```btafel:accounts-facebook-cordova``` doesn't use because of a bug in the Meteor + Ionic 2 combo (```btafel:accounts-facebook-cordova``` expects to be able to access ```Meteor.settings.public``` on the client, while ```Meteor.settings``` is ```undefined``` because meteor-client-bundler does not have the ```--settings``` parameter poiting to the settings file).
It's pretty easy to workaround it and make it work, but since in my opinion ```btafel:accounts-facebook-cordova``` is not so well designed (and doesn't have a nice API to work with from external packages) I decided to rewrite some parts of the package. This is mandatory to make it work with packages like ```yubozhao:meteor-link-accounts``` which otherwise falls back to the Browser Facebook API.
Let me know if you need help with the "dirty hack" or if you prefer to wait for my own version of the package.

**Comment by darkbasic** [comment]
@ingleo have a look at my latest post: [https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/40](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/40)
I didn't rewrite ```accounts-facebook``` as I wished to do, because it probably would be a waste of time without some kind of official support for accounts linking in Meteor. So most of the work is in ```meteor-link-accounts``` instead.

**Comment by ingleo** [comment]
Hi @darkbasic I had read #40 latest posts and I'm little confused, can you tell me please if:
```meteor-link-accounts```: https://github.com/darkbasic/meteor-link-accounts
```accounts-facebook```: https://github.com/darkbasic/accounts-facebook
Both resolve this issue , or resolve different cases according that you say in the post.
Really appreciate your help with this.

**Comment by darkbasic** [comment]
If you only need facebook authentication you can safely use only ```darkbasic:accounts-facebook```. On Cordova it will work out of the box, while on Browser you will need an nginx proxy.
You will need ```meteor-link-accounts``` only if you want to **link** an existing account with a Facebook account.
Both had issues with angular-meteor, which I fixed.

**Comment by ingleo** [comment]
When you say "link", is that the facebook user data will be stored in Meteor users colllection?

**Comment by darkbasic** [comment]
With account linking I mean allowing a user to authenticate from any of their accounts and still be recognized by your app and associated with the same user profile.

Meteor will treat all identities as separate by default. For example: if a user logs in first using its username and password and then via Google or Facebook, these two attempts would appear to Meteor as two separate users.

**Comment by ingleo** [comment]
Thank you so much for your help, now is clear to me every one, how do you do for call ```darkbasic:accounts-facebook-cordova``` packages locally,  if it's not available in atmosphere?

**Comment by darkbasic** [comment]
Just clone the repo into ```./api/packages/``` and then ```meteor add darkbasic:accounts-facebook-cordova```. By the way you don't need ```darkbasic:accounts-facebook-cordova``` anymore because they just merged my commit [upstream](https://github.com/btafel/accounts-facebook/pull/2#event-1073354479).

**Comment by ingleo** [comment]
Hi @darkbasic, I'm going to install the package updated, and tell you if it works fine.
By the way, I was looking for your pull request on yubozhao/meteor-link-accounts and found that your changes reference the "darkbasic:accounts-facebook-cordova" package, according to your comment above, already isn't necesary.

**Comment by ingleo** [comment]
I'm able to login with facebook now using ```btafel:accounts-facebook-cordova``` local package, but it was necessary copy the generated source code by the meteor startup into the file generated by the ```meteor-client-bundler``` in order to have the latest changes that support the login options.
Thank you so much @darkbasic, regards.
I'm going to close the issue.

**Comment by darkbasic** [comment]
You're welcome ;)

**Comment by LdwgWffnschmdt** [comment]
Hey, I'm trying to get only Facebook login to work, without any account linking and I'm failing completely. Could one of you maybe give me a quick explanation on how to replace the phone authentication step in the tutorial with a simple facebook login that uses the native FB API in Cordova and a fallback in browser? That would be huge.

**Comment by darkbasic** [comment]
That's exactly what [chapter 17](https://angular-meteor.com/tutorials/whatsapp2/ionic/facebook) up to 17.7 does.

**Comment by LdwgWffnschmdt** [comment]
Yes, I found that too, and I also got it working in the emulator, but could you maybe give me a quick heads up on this whole nginx proxy stuff? That's still a riddle to me.

**Comment by darkbasic** [comment]
Nginx is only needed for the brower facebook auth, not the cordova one. The problem is that the facebook landing page listens on port 3000 on the server, while the rest of the app runs on a different port (Ionic 8100).

**Comment by shyne99** [comment]
Hello,
I've read all your comments related to this issue. And their is something that bugs me. 

OAuth is supposed to respond to the user adress. I don't quiet understand what nginx is doing in this. I understand that the proxy is here to redirect some of the request to either the client or the server but the servername is never gona be resolve. Nobody know that the connection made to this url are supposed to be handled by the local nginx. 

I really don't understand this specific part. If someone can explain it please. 
Thank you
