### ISSUE TITLE
"Uncaught ReferenceError: __meteor_runtime_config__ is not defined" when trying to run on emulator

### ISSUE THREAD

**Issue by y01s** [Urigo/Ionic2CLI-Meteor-WhatsApp#94]
The problem occurs in step 4.
when I ran `ionic serve` everything works fine, but when trying to run on android 
`ionic run android`, 
I get a white screen, and in the console I get this

`Uncaught ReferenceError: __meteor_runtime_config__ is not defined`

How can I solve this?

**Comment by dcousens** [comment]
How did you resolve this?

**Comment by hayk94** [comment]
Can you help me with this guys?
